language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio

script:
  - platformio run && pwd && ls -al .pioenvs/sonoff/

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "/home/travis/build/roondar/Sonoff-Tasmota/.pioenvs/sonoff/firmware.bin"
  draft: true
