language: python
python:
  - '2.7'
sudo: false
install:
  - pip install -U platformio
  - mkdir /tmp/build

script:
  - platformio run --build-dir="/tmp/build"  --keep-build-dir
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "/tmp/build/.pioenvs/sonoff/firmware.bin"
  draft: true
